apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache-deployment
spec:
  replicas: 3  # Set the number of replicas as needed
  selector:
    matchLabels:
      app: php-apache
  template:
    metadata:
      labels:
        app: php-apache
    spec:
      containers:
        - name: php-apache-container
          image: jahirraihan/php-apache2:v-php8.1
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: php-apache-service
spec:
  selector:
    app: php-apache
  ports:
    - nodePort: 32566
      protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
